version: "3.4"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ../Dockerfile.backend
    restart: always
    volumes:
      - ./volumes/static:/var/static/
      - ./volumes/media:/var/media/
    env_file:
      - ./backend/.env
    environment:
      STATIC_ROOT: /var/static
      MEDIA_ROOT: /var/media
    depends_on:
      - postgres
      - redis
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && uvicorn config.asgi:application --host 0.0.0.0 --port 80 --workers ${WORKERS:-1}" --no-access-log
    networks:
      - backend-network
      - nginx-proxy
    expose:
      - "80"

  postgres:
    image: postgres:15
    env_file: postgres.env
    networks:
      - backend-network
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/

  redis:
    image: redis
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
  nginx-proxy:
    external: true
