FROM python:3.11-slim

WORKDIR /code/backend/

# Install uvicorn
RUN pip install --upgrade pip && pip install uvicorn

# Install python requirements
COPY requirements* ./
RUN pip install -r requirements-production.txt

# Copy Django code
COPY . .